#!/usr/bin/env python3
"""
Scrape AV Global MBBS country guide pages into a fixed JSON/workbook schema.

The Laravel MBBS country pages consume the content JSON generated by this
script. The admin sync tool runs the same script in review mode, compares the
fresh scrape with the live file, and lets the admin apply changes.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
import time
from collections import OrderedDict
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, unquote, urljoin, urlparse

import requests
from bs4 import BeautifulSoup, NavigableString, Tag
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, OSError):
    pass


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://www.avglobaloverseas.com"
DEFAULT_SEED_URL = BASE_URL + "/study-mbbs-abroad/mbbs-in-georgia"
DEFAULT_OUTPUT = PROJECT_ROOT / "storage" / "app" / "mbbs_avglobal_content.xlsx"
SCHEMA_VERSION = "2026-06-08.avglobal.1"
USER_AGENT = (
    "Mozilla/5.0 (compatible; OneDegree-MBBSCountrySync/1.0; +https://onedegreeadvisory.com)"
)

COUNTRY_URL_RE = re.compile(r"^/study-mbbs-abroad/mbbs-in-([a-z0-9-]+)/?$", re.I)
FLAG_RE = re.compile(r"/([A-Z]{2})\.svg(?:$|\?)")
ADMISSION_HEADING_RE = re.compile(r"\badmission\s+process\b|\bhow\s+to\s+apply\b", re.I)

EXCEL_CELL_LIMIT = 32767
SAFE_CELL_LIMIT = 32000
ILLEGAL_EXCEL_RE = re.compile(r"[\x00-\x08\x0b-\x0c\x0e-\x1f]")
VOLATILE_COMPARE_FIELDS = {"fetched_at_utc", "row_sha256"}

DATA_SHEETS = ["Pages", "Sections", "Bullets", "Subpoints", "Facts", "AdmissionSteps"]

CONTENT_WORKBOOK_SCHEMAS: "OrderedDict[str, list[str]]" = OrderedDict(
    [
        (
            "Pages",
            [
                "country",
                "page_slug",
                "page_url",
                "source_url",
                "flag_code",
                "flag_url",
                "hero_image",
                "page_title",
                "hero_heading",
                "hero_text",
                "source_updated",
            ],
        ),
        (
            "Sections",
            [
                "country",
                "page_slug",
                "section_order",
                "section_key",
                "section_heading",
                "section_body",
            ],
        ),
        (
            "Bullets",
            [
                "country",
                "page_slug",
                "section_key",
                "bullet_order",
                "bullet_text",
            ],
        ),
        (
            "Subpoints",
            [
                "country",
                "page_slug",
                "section_key",
                "subpoint_order",
                "subpoint_heading",
                "subpoint_body",
            ],
        ),
        (
            "Facts",
            [
                "country",
                "page_slug",
                "fact_order",
                "fact_label",
                "fact_value",
            ],
        ),
        (
            "AdmissionSteps",
            [
                "country",
                "page_slug",
                "step_order",
                "step_title",
                "step_body",
            ],
        ),
    ]
)

CHANGE_REPORT_SCHEMAS: "OrderedDict[str, list[str]]" = OrderedDict(
    [
        ("Change_Summary", ["metric", "value"]),
        (
            "Pending_Changes",
            [
                "change_type",
                "sheet",
                "country",
                "record_id",
                "field",
                "old_content",
                "new_content",
            ],
        ),
    ]
)


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def make_run_id() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    text = str(value)
    text = ILLEGAL_EXCEL_RE.sub(" ", text)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\s+([?.!,;:])", r"\1", text)
    return text


def excel_safe(value: Any) -> str:
    text = clean_text(value)
    if len(text) <= EXCEL_CELL_LIMIT:
        return text
    return f"{text[:SAFE_CELL_LIMIT]} ... [TRUNCATED original_char_count={len(text)}]"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def stable_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def row_hash(row: dict[str, Any]) -> str:
    comparable = {k: clean_text(v) for k, v in row.items() if k not in VOLATILE_COMPARE_FIELDS}
    return sha256_text(stable_json(comparable))


def add_hash(row: dict[str, Any]) -> dict[str, Any]:
    out = dict(row)
    out["row_sha256"] = row_hash(out)
    return out


def slug_from_country_name(name: str) -> str:
    text = clean_text(name).lower()
    text = text.replace("&", " and ")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def country_from_slug(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.split("-") if part)


def heading_level(tag: Tag) -> int:
    name = (tag.name or "").lower()
    if len(name) == 2 and name[0] == "h" and name[1].isdigit():
        return int(name[1])
    return 0


def is_heading(tag: Tag, names: set[str] | None = None) -> bool:
    if names is not None:
        return (tag.name or "").lower() in names
    return heading_level(tag) > 0


def direct_li_text(li: Tag) -> str:
    parts: list[str] = []
    for child in li.children:
        if isinstance(child, NavigableString):
            parts.append(str(child))
        elif isinstance(child, Tag):
            if child.name in ("ul", "ol"):
                continue
            parts.append(child.get_text(" ", strip=True))
    return clean_text(" ".join(parts))


def decode_image_url(src: str, page_url: str) -> str:
    src = clean_text(src)
    if src == "":
        return ""
    parsed = urlparse(src)
    if parsed.path == "/_next/image":
        original = parse_qs(parsed.query).get("url", [""])[0]
        if original:
            src = unquote(original)
    return urljoin(page_url, src)


def flag_code_from_image(img: Tag | None) -> tuple[str, str]:
    if img is None:
        return "", ""
    src = decode_image_url((img.get("src") or ""), BASE_URL)
    alt = clean_text(img.get("alt", ""))

    match = FLAG_RE.search(src)
    if match:
        return match.group(1).lower(), src

    alt_match = re.match(r"^([A-Z]{2})\s+flag$", alt)
    if alt_match:
        return alt_match.group(1).lower(), src

    return "", src


def country_slug_from_url(url: str) -> str:
    path = urlparse(url).path
    match = COUNTRY_URL_RE.match(path)
    return match.group(1).lower() if match else ""


def normalize_country_name(text: str, slug: str) -> str:
    name = clean_text(text)
    name = re.sub(r"^MBBS\s+in\s+", "", name, flags=re.I)
    name = re.sub(r"\s*-\s*Complete\s+Guide$", "", name, flags=re.I)
    if not name or len(name) > 45:
        name = country_from_slug(slug)
    return name


def section_key_for_heading(heading: str) -> str:
    text = clean_text(heading).lower()
    if "quick facts" in text:
        return "quick_facts"
    if "nmc" in text and ("gazette" in text or "compliance" in text):
        return "nmc_compliance"
    if "eligibility" in text:
        return "eligibility"
    if "admission process" in text or "how to apply" in text:
        return "admission_process"
    if "universit" in text:
        return "universities"
    if "cost" in text or "fees" in text or "budget" in text:
        return "cost"
    if "comparison" in text or " vs " in text:
        return "comparison"
    if "daily life" in text or "student life" in text:
        return "student_life"
    if "frequently asked" in text or "faq" in text:
        return "faq"
    if "right choice" in text or "honest assessment" in text:
        return "fit_assessment"
    return slug_from_country_name(heading)[:80] or "section"


def fetch_html(session: requests.Session, url: str, timeout: int) -> tuple[str, int, str]:
    response = session.get(url, timeout=timeout)
    response.raise_for_status()
    if not response.encoding or response.encoding.lower() == "iso-8859-1":
        response.encoding = response.apparent_encoding or "utf-8"
    return response.text, response.status_code, response.url


def extract_country_links_from_menu(soup: BeautifulSoup, seed_url: str) -> list[dict[str, str]]:
    grid: Tag | None = None
    for h in soup.find_all(["h3", "h4", "h5"]):
        if clean_text(h.get_text(" ", strip=True)).upper() != "EXPLORE COUNTRIES":
            continue
        for node in h.find_all_next("div", limit=8):
            classes = " ".join(node.get("class", []))
            if "grid" in classes:
                grid = node
                break
        if grid is not None:
            break

    if grid is None:
        return []

    links: list[dict[str, str]] = []
    seen: set[str] = set()
    for a in grid.find_all("a", href=True):
        url = urljoin(seed_url, a["href"])
        slug = country_slug_from_url(url)
        if slug == "" or slug in seen:
            continue
        name = normalize_country_name(a.get_text(" ", strip=True), slug)
        flag_code, flag_url = flag_code_from_image(a.find("img"))
        links.append(
            {
                "name": name,
                "slug": slug,
                "url": url,
                "flag_code": flag_code,
                "flag_url": flag_url,
            }
        )
        seen.add(slug)

    return links


def extract_country_links_fallback(soup: BeautifulSoup, seed_url: str) -> list[dict[str, str]]:
    links: list[dict[str, str]] = []
    seen: set[str] = set()
    for a in soup.find_all("a", href=True):
        url = urljoin(seed_url, a["href"])
        slug = country_slug_from_url(url)
        if slug == "" or slug in seen:
            continue
        name = normalize_country_name(a.get_text(" ", strip=True), slug)
        if name.lower() in {"view all countries", "study mbbs abroad"}:
            continue
        flag_code, flag_url = flag_code_from_image(a.find("img"))
        links.append(
            {
                "name": name,
                "slug": slug,
                "url": url,
                "flag_code": flag_code,
                "flag_url": flag_url,
            }
        )
        seen.add(slug)
    return links


def discover_country_pages(session: requests.Session, seed_url: str, timeout: int) -> list[dict[str, str]]:
    print(f"Discovering MBBS country URLs from {seed_url}")
    html, _status, final_url = fetch_html(session, seed_url, timeout)
    soup = BeautifulSoup(html, "lxml")
    links = extract_country_links_from_menu(soup, final_url)
    if not links:
        links = extract_country_links_fallback(soup, final_url)
    if not links:
        slug = country_slug_from_url(final_url) or "georgia"
        links = [{"name": country_from_slug(slug), "slug": slug, "url": final_url, "flag_code": "", "flag_url": ""}]
    print(f"Discovered {len(links)} MBBS country page(s).")
    return links


def first_meta_description(soup: BeautifulSoup) -> str:
    meta = soup.find("meta", attrs={"name": "description"})
    if meta and meta.get("content"):
        return clean_text(meta["content"])
    og = soup.find("meta", attrs={"property": "og:description"})
    if og and og.get("content"):
        return clean_text(og["content"])
    return ""


def source_updated_text(main: Tag) -> str:
    month_year = re.compile(r"last\s+updated\s*:\s*([A-Za-z]+\s+\d{4})", re.I)
    pattern = re.compile(r"last\s+updated\s*:\s*(.+)", re.I)
    compact = clean_text(main.get_text(" ", strip=True))
    exact = month_year.search(compact)
    if exact:
        return exact.group(1)
    for node in main.find_all(string=pattern):
        match = pattern.search(clean_text(node))
        if match:
            return match.group(1)[:80]
    match = pattern.search(compact)
    return match.group(1)[:80] if match else ""


def hero_image(main: Tag, country: str, page_url: str) -> str:
    h1 = main.find("h1")
    hero = h1.find_parent("section") if h1 else None
    candidates = (hero.find_all("img") if hero else main.find_all("img", limit=12))
    country_l = country.lower()
    for img in candidates:
        alt = clean_text(img.get("alt", ""))
        src = decode_image_url((img.get("src") or ""), page_url)
        if src and "flag" not in alt.lower() and (country_l in alt.lower() or alt):
            return src
    return ""


def page_flag(main: Tag, fallback_code: str, fallback_url: str) -> tuple[str, str]:
    if fallback_code or fallback_url:
        return fallback_code, fallback_url
    for img in main.find_all("img"):
        code, url = flag_code_from_image(img)
        if code:
            return code, url
    return "", ""


def tags_until_next_h2(start: Tag) -> list[Tag]:
    tags: list[Tag] = []
    container = start.find_parent("section") or start.find_parent("main")
    for node in start.next_elements:
        if node is start:
            continue
        if not isinstance(node, Tag):
            continue
        if container is not None and node is not container and container not in node.parents:
            break
        if node.name == "h2":
            break
        if node.name in ("script", "style", "noscript", "svg"):
            continue
        tags.append(node)
    return tags


def unique_append(items: list[str], text: str, max_items: int | None = None) -> None:
    text = clean_text(text)
    if text == "":
        return
    if text in items:
        return
    if max_items is not None and len(items) >= max_items:
        return
    items.append(text)


def collect_text_chunks_after_h2(h2: Tag) -> list[str]:
    chunks: list[str] = []
    for tag in tags_until_next_h2(h2):
        if tag.name in ("p", "blockquote"):
            unique_append(chunks, tag.get_text(" ", strip=True), 48)
        elif tag.name == "li":
            unique_append(chunks, direct_li_text(tag), 48)
        elif tag.name == "table":
            for tr in tag.find_all("tr"):
                cells = [clean_text(td.get_text(" ", strip=True)) for td in tr.find_all(["td", "th"])]
                cells = [c for c in cells if c]
                if cells:
                    unique_append(chunks, " | ".join(cells), 48)
    return chunks


def collect_bullets_after_h2(h2: Tag) -> list[str]:
    bullets: list[str] = []
    for tag in tags_until_next_h2(h2):
        if tag.name == "li":
            unique_append(bullets, direct_li_text(tag))
    return bullets


def collect_subpoints_after_h2(h2: Tag, section_key: str) -> list[dict[str, str]]:
    subpoints: list[dict[str, str]] = []
    current_heading = ""
    current_parts: list[str] = []

    def flush() -> None:
        nonlocal current_heading, current_parts
        body = " ".join(current_parts).strip()
        if current_heading or body:
            subpoints.append({"heading": current_heading, "body": excel_safe(body), "section_key": section_key})
        current_heading = ""
        current_parts = []

    for tag in tags_until_next_h2(h2):
        if tag.name in ("h3", "h4"):
            flush()
            current_heading = clean_text(tag.get_text(" ", strip=True))
            continue
        if current_heading == "":
            continue
        if tag.name in ("p", "blockquote"):
            unique_append(current_parts, tag.get_text(" ", strip=True), 16)
        elif tag.name == "li":
            unique_append(current_parts, direct_li_text(tag), 24)
        elif tag.name == "table":
            for tr in tag.find_all("tr"):
                cells = [clean_text(td.get_text(" ", strip=True)) for td in tr.find_all(["td", "th"])]
                cells = [c for c in cells if c]
                if cells:
                    unique_append(current_parts, " | ".join(cells), 24)

    flush()
    return [sp for sp in subpoints if sp["heading"] or sp["body"]]


def extract_quick_facts(main: Tag, country: str, slug: str) -> list[dict[str, Any]]:
    h2 = None
    for candidate in main.find_all("h2"):
        if "quick facts" in clean_text(candidate.get_text(" ", strip=True)).lower():
            h2 = candidate
            break
    if h2 is None:
        return []

    section = h2.find_parent("section") or h2.parent
    facts: list[dict[str, Any]] = []
    seen: set[str] = set()

    for card in section.find_all("div"):
        ps = card.find_all("p", recursive=False)
        if len(ps) < 2:
            continue
        label = clean_text(ps[0].get_text(" ", strip=True))
        value = clean_text(ps[1].get_text(" ", strip=True))
        key = label.lower()
        if label == "" or value == "" or key in seen:
            continue
        facts.append(
            add_hash(
                {
                    "record_id": f"fact|{slug}|{len(facts) + 1:02d}",
                    "country": country,
                    "page_slug": slug,
                    "fact_order": len(facts) + 1,
                    "fact_label": label,
                    "fact_value": excel_safe(value),
                }
            )
        )
        seen.add(key)

    return facts


def extract_intro_section(main: Tag, country: str, slug: str) -> dict[str, Any] | None:
    first_content_h2 = None
    for h2 in main.find_all("h2"):
        text = clean_text(h2.get_text(" ", strip=True)).lower()
        if "quick facts" not in text:
            first_content_h2 = h2
            break
    if first_content_h2 is None:
        return None

    section = first_content_h2.find_parent("section")
    if section is None:
        return None

    chunks: list[str] = []
    for tag in section.descendants:
        if tag is first_content_h2:
            break
        if not isinstance(tag, Tag):
            continue
        if tag.name in ("p", "blockquote"):
            unique_append(chunks, tag.get_text(" ", strip=True), 8)

    body = " ".join(chunks).strip()
    if body == "":
        return None

    return add_hash(
        {
            "record_id": f"section|{slug}|for_indian_students",
            "country": country,
            "page_slug": slug,
            "section_order": 1,
            "section_key": "for_indian_students",
            "section_heading": f"MBBS in {country} for Indian students",
            "section_body": excel_safe(body),
        }
    )


def extract_admission_steps(h2: Tag, country: str, slug: str) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []
    current_title = ""
    current_parts: list[str] = []

    def flush() -> None:
        nonlocal current_title, current_parts
        if current_title:
            steps.append(
                add_hash(
                    {
                        "record_id": f"step|{slug}|{len(steps) + 1:02d}",
                        "country": country,
                        "page_slug": slug,
                        "step_order": len(steps) + 1,
                        "step_title": current_title,
                        "step_body": excel_safe(" | ".join(current_parts)),
                    }
                )
            )
        current_title = ""
        current_parts = []

    for tag in tags_until_next_h2(h2):
        if tag.name in ("h3", "h4"):
            flush()
            current_title = clean_text(tag.get_text(" ", strip=True))
            continue
        if current_title == "":
            continue
        if tag.name == "li":
            unique_append(current_parts, direct_li_text(tag), 12)
        elif tag.name in ("p", "blockquote"):
            unique_append(current_parts, tag.get_text(" ", strip=True), 12)

    flush()
    return steps


def parse_country_page(country: dict[str, str], html: str, page_url: str) -> dict[str, list[dict[str, Any]]]:
    soup = BeautifulSoup(html, "lxml")
    main = soup.find("main") or soup

    slug = country["slug"]
    name = country["name"]
    page_title = clean_text(soup.title.get_text(" ", strip=True)) if soup.title else f"MBBS in {name}"
    h1 = main.find("h1")
    hero_heading = clean_text(h1.get_text(" ", strip=True)) if h1 else f"MBBS in {name}"
    flag_code, flag_url = page_flag(main, country.get("flag_code", ""), country.get("flag_url", ""))

    sheets: dict[str, list[dict[str, Any]]] = {sheet: [] for sheet in DATA_SHEETS}
    sheets["Pages"].append(
        add_hash(
            {
                "record_id": f"page|{slug}",
                "country": name,
                "page_slug": slug,
                "page_url": page_url,
                "source_url": country.get("url", page_url),
                "flag_code": flag_code,
                "flag_url": flag_url,
                "hero_image": hero_image(main, name, page_url),
                "page_title": page_title,
                "hero_heading": hero_heading,
                "hero_text": excel_safe(first_meta_description(soup)),
                "source_updated": source_updated_text(main),
            }
        )
    )

    sheets["Facts"].extend(extract_quick_facts(main, name, slug))

    section_order = 0
    intro = extract_intro_section(main, name, slug)
    if intro is not None:
        section_order += 1
        intro["section_order"] = section_order
        sheets["Sections"].append(intro)

    seen_section_keys: dict[str, int] = {}
    for h2 in main.find_all("h2"):
        heading = clean_text(h2.get_text(" ", strip=True))
        if heading == "" or "quick facts" in heading.lower():
            continue
        base_key = section_key_for_heading(heading)
        seen_section_keys[base_key] = seen_section_keys.get(base_key, 0) + 1
        section_key = base_key if seen_section_keys[base_key] == 1 else f"{base_key}_{seen_section_keys[base_key]}"
        chunks = collect_text_chunks_after_h2(h2)
        bullets = collect_bullets_after_h2(h2)
        subpoints = collect_subpoints_after_h2(h2, section_key)

        section_order += 1
        sheets["Sections"].append(
            add_hash(
                {
                    "record_id": f"section|{slug}|{section_key}",
                    "country": name,
                    "page_slug": slug,
                    "section_order": section_order,
                    "section_key": section_key,
                    "section_heading": heading,
                    "section_body": excel_safe(" ".join(chunks)),
                }
            )
        )

        for index, bullet in enumerate(bullets, 1):
            sheets["Bullets"].append(
                add_hash(
                    {
                        "record_id": f"bullet|{slug}|{section_key}|{index:02d}",
                        "country": name,
                        "page_slug": slug,
                        "section_key": section_key,
                        "bullet_order": index,
                        "bullet_text": excel_safe(bullet),
                    }
                )
            )

        for index, sp in enumerate(subpoints, 1):
            sheets["Subpoints"].append(
                add_hash(
                    {
                        "record_id": f"subpoint|{slug}|{section_key}|{index:02d}",
                        "country": name,
                        "page_slug": slug,
                        "section_key": section_key,
                        "subpoint_order": index,
                        "subpoint_heading": sp["heading"],
                        "subpoint_body": sp["body"],
                    }
                )
            )

        if ADMISSION_HEADING_RE.search(heading):
            sheets["AdmissionSteps"].extend(extract_admission_steps(h2, name, slug))

    return sheets


def build_dataset(args: argparse.Namespace, countries: list[dict[str, str]]) -> dict[str, Any]:
    session = requests.Session()
    session.headers.update({"User-Agent": USER_AGENT, "Accept-Language": "en-US,en;q=0.9"})

    if not countries:
        countries = discover_country_pages(session, args.seed_url, args.timeout)

    if args.country:
        wanted = {slug_from_country_name(c).lower() for c in args.country}
        countries = [c for c in countries if c["slug"].lower() in wanted]
        if not countries:
            raise RuntimeError(f"No matching countries for --country {args.country}")

    sheets: dict[str, list[dict[str, Any]]] = {sheet: [] for sheet in DATA_SHEETS}
    fetched_at = utc_now()
    fetched_countries: list[str] = []

    for index, country in enumerate(countries, 1):
        print(f"[{index}/{len(countries)}] Fetching {country['url']}")
        try:
            html, status, final_url = fetch_html(session, country["url"], args.timeout)
        except requests.RequestException as exc:
            print(f"  - skipped: {exc}")
            continue
        if status >= 400:
            print(f"  - skipped: {country['slug']} returned {status}")
            continue
        parsed = parse_country_page(country, html, final_url)
        for sheet in DATA_SHEETS:
            sheets[sheet].extend(parsed.get(sheet, []))
        fetched_countries.append(country["slug"])
        if args.delay and index < len(countries):
            time.sleep(args.delay)

    dataset = {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": fetched_at,
        "source": BASE_URL,
        "seed_url": args.seed_url,
        "country_urls": [c["url"] for c in countries],
        "countries_scraped": fetched_countries,
        "sheets": sheets,
    }
    dataset["snapshot_sha256"] = dataset_hash(dataset)
    return dataset


def comparable_map(dataset: dict[str, Any]) -> dict[str, dict[str, Any]]:
    output: dict[str, dict[str, Any]] = {}
    for sheet_name in DATA_SHEETS:
        for row in dataset.get("sheets", {}).get(sheet_name, []):
            record_id = row.get("record_id", "")
            key = f"{sheet_name}::{record_id}"
            output[key] = {k: clean_text(v) for k, v in row.items() if k not in VOLATILE_COMPARE_FIELDS}
    return output


def dataset_hash(dataset: dict[str, Any]) -> str:
    return sha256_text(stable_json(comparable_map(dataset)))


def summarize_records(dataset: dict[str, Any]) -> int:
    return sum(len(dataset.get("sheets", {}).get(s, [])) for s in DATA_SHEETS)


def row_country(row: dict[str, Any]) -> str:
    return clean_text(row.get("country", ""))


def compact_row_value(row: dict[str, Any]) -> str:
    preferred = [
        "country",
        "page_slug",
        "section_key",
        "section_heading",
        "bullet_text",
        "subpoint_heading",
        "fact_label",
        "fact_value",
        "step_title",
    ]
    summary = {k: row.get(k, "") for k in preferred if row.get(k, "") not in ("", None)}
    return excel_safe(stable_json(summary) if summary else stable_json(row))


def compare_datasets(old: dict[str, Any] | None, new: dict[str, Any], run_id: str) -> dict[str, Any]:
    if not old:
        records_after = summarize_records(new)
        return {
            "has_changes": True,
            "summary": {
                "records_before": 0,
                "records_after": records_after,
                "added_records": records_after,
                "removed_records": 0,
                "modified_records": 0,
                "changed_records": records_after,
                "changed_percent": 100.0 if records_after else 0.0,
            },
            "detail_rows": [],
        }

    old_map = comparable_map(old)
    new_map = comparable_map(new)
    added = sorted(set(new_map) - set(old_map))
    removed = sorted(set(old_map) - set(new_map))
    modified = sorted(k for k in set(old_map) & set(new_map) if old_map[k] != new_map[k])

    detail_rows: list[dict[str, Any]] = []
    for key in added:
        sheet, record_id = key.split("::", 1)
        row = new_map[key]
        detail_rows.append(
            {
                "run_id": run_id,
                "change_type": "added",
                "sheet": sheet,
                "record_id": record_id,
                "country": row_country(row),
                "field": "__row__",
                "old_value": "",
                "new_value": compact_row_value(row),
            }
        )
    for key in removed:
        sheet, record_id = key.split("::", 1)
        row = old_map[key]
        detail_rows.append(
            {
                "run_id": run_id,
                "change_type": "removed",
                "sheet": sheet,
                "record_id": record_id,
                "country": row_country(row),
                "field": "__row__",
                "old_value": compact_row_value(row),
                "new_value": "",
            }
        )
    for key in modified:
        sheet, record_id = key.split("::", 1)
        old_row = old_map[key]
        new_row = new_map[key]
        for field in sorted(set(old_row) | set(new_row)):
            if clean_text(old_row.get(field, "")) == clean_text(new_row.get(field, "")):
                continue
            detail_rows.append(
                {
                    "run_id": run_id,
                    "change_type": "modified",
                    "sheet": sheet,
                    "record_id": record_id,
                    "country": row_country(new_row) or row_country(old_row),
                    "field": field,
                    "old_value": excel_safe(old_row.get(field, "")),
                    "new_value": excel_safe(new_row.get(field, "")),
                }
            )

    changed_records = len(added) + len(removed) + len(modified)
    denominator = max(len(old_map), len(new_map), 1)
    return {
        "has_changes": changed_records > 0,
        "summary": {
            "records_before": len(old_map),
            "records_after": len(new_map),
            "added_records": len(added),
            "removed_records": len(removed),
            "modified_records": len(modified),
            "changed_records": changed_records,
            "changed_percent": round((changed_records / denominator) * 100, 2),
        },
        "detail_rows": detail_rows,
    }


def load_snapshot(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def save_snapshot(path: Path, dataset: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(dataset, ensure_ascii=False, indent=2), encoding="utf-8")


def normalized_sheet_rows(rows: list[dict[str, Any]], headers: list[str]) -> list[list[Any]]:
    return [[row.get(header, "") for header in headers] for row in rows]


def apply_sheet_style(ws, sheet_name: str) -> None:
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(bold=True, color="FFFFFF")
    ws.freeze_panes = "A2"
    if ws.max_row >= 1 and ws.max_column >= 1:
        ws.auto_filter.ref = ws.dimensions

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    width_caps = {
        "Sections": 72,
        "Bullets": 72,
        "Subpoints": 72,
        "Facts": 50,
        "AdmissionSteps": 64,
    }
    cap = width_caps.get(sheet_name, 44)
    for col_idx, column_cells in enumerate(ws.columns, 1):
        header = clean_text(ws.cell(row=1, column=col_idx).value)
        max_len = len(header)
        count = 0
        for cell in column_cells:
            if cell.row == 1:
                continue
            max_len = max(max_len, min(len(clean_text(cell.value)), cap))
            count += 1
            if count >= 250:
                break
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(max_len + 2, 14), cap)


def write_rows_workbook(
    path: Path,
    schemas: "OrderedDict[str, list[str]]",
    sheet_rows: dict[str, list[dict[str, Any]]],
) -> None:
    wb = Workbook()
    default = wb.active
    wb.remove(default)
    for sheet_name, headers in schemas.items():
        ws = wb.create_sheet(sheet_name)
        ws.append(headers)
        for values in normalized_sheet_rows(sheet_rows.get(sheet_name, []), headers):
            ws.append(values)
        apply_sheet_style(ws, sheet_name)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)


def content_rows(dataset: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    sheets = dataset.get("sheets", {})
    rows: dict[str, list[dict[str, Any]]] = {sheet: [] for sheet in CONTENT_WORKBOOK_SCHEMAS}
    for sheet, headers in CONTENT_WORKBOOK_SCHEMAS.items():
        for row in sheets.get(sheet, []):
            rows[sheet].append({header: row.get(header, "") for header in headers})
    return rows


def write_content_json(path: Path, dataset: dict[str, Any]) -> None:
    payload = {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": dataset.get("generated_at_utc", ""),
        "source": dataset.get("source", BASE_URL),
        "seed_url": dataset.get("seed_url", DEFAULT_SEED_URL),
        "country_urls": dataset.get("country_urls", []),
        "countries_scraped": dataset.get("countries_scraped", []),
        "sheets": content_rows(dataset),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_workbook(path: Path, dataset: dict[str, Any]) -> None:
    write_rows_workbook(path, CONTENT_WORKBOOK_SCHEMAS, content_rows(dataset))


def write_change_report(path: Path, comparison: dict[str, Any]) -> None:
    summary = comparison.get("summary", {})
    summary_rows = [
        {"metric": "changed_percent", "value": summary.get("changed_percent", "")},
        {"metric": "added_records", "value": summary.get("added_records", "")},
        {"metric": "removed_records", "value": summary.get("removed_records", "")},
        {"metric": "modified_records", "value": summary.get("modified_records", "")},
        {"metric": "records_before", "value": summary.get("records_before", "")},
        {"metric": "records_after", "value": summary.get("records_after", "")},
    ]
    pending_rows = [
        {
            "change_type": d.get("change_type", ""),
            "sheet": d.get("sheet", ""),
            "country": d.get("country", ""),
            "record_id": d.get("record_id", ""),
            "field": d.get("field", ""),
            "old_content": d.get("old_value", ""),
            "new_content": d.get("new_value", ""),
        }
        for d in comparison.get("detail_rows", [])
    ]
    write_rows_workbook(path, CHANGE_REPORT_SCHEMAS, {"Change_Summary": summary_rows, "Pending_Changes": pending_rows})


def print_change_summary(comparison: dict[str, Any], report_path: Path | None = None) -> None:
    summary = comparison["summary"]
    print(
        f"Change summary: {summary['changed_records']} changed record(s) ({summary['changed_percent']}%). "
        f"Added={summary['added_records']}, Removed={summary['removed_records']}, Modified={summary['modified_records']}."
    )
    details = comparison.get("detail_rows", [])
    if details:
        print("First changes:")
        for row in details[:15]:
            old = clean_text(row.get("old_value", ""))[:90]
            new = clean_text(row.get("new_value", ""))[:90]
            print(f"  - {row['change_type']} | {row['sheet']} | {row['record_id']} | {row['field']} | {old!r} -> {new!r}")
        if len(details) > 15:
            print(f"  ... {len(details) - 15} more change(s).")
    if report_path:
        print(f"Pending change report: {report_path}")


def prompt_approval() -> bool:
    answer = input("Approve replacing the existing workbook and snapshot? [y/N]: ").strip().lower()
    return answer in {"y", "yes"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scrape MBBS country pages from AV Global Overseas.")
    parser.add_argument("--seed-url", default=DEFAULT_SEED_URL, help="Starting AV Global MBBS country URL.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Excel workbook path.")
    parser.add_argument("--snapshot", type=Path, default=None, help="Snapshot JSON path.")
    parser.add_argument("--content-json", type=Path, default=None, help="Content JSON path consumed by the app.")
    parser.add_argument("--report", type=Path, default=None, help="Pending change report path.")
    parser.add_argument("--approve", action="store_true", help="Auto-approve workbook replacement.")
    parser.add_argument("--no-approve", action="store_true", help="Never replace the workbook; only emit the change report.")
    parser.add_argument("--force", action="store_true", help="Rewrite workbook even if data is unchanged.")
    parser.add_argument("--delay", type=float, default=0.2, help="Delay between requests in seconds.")
    parser.add_argument("--timeout", type=int, default=40, help="HTTP timeout in seconds.")
    parser.add_argument("--country", action="append", default=None, help="Restrict to a country slug (repeatable).")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.approve and args.no_approve:
        print("Use either --approve or --no-approve, not both.", file=sys.stderr)
        return 2

    output_path = args.output.resolve()
    snapshot_path = args.snapshot.resolve() if args.snapshot else output_path.with_name(f"{output_path.stem}.snapshot.json")
    content_json_path = args.content_json.resolve() if args.content_json else output_path.with_suffix(".json")
    report_path = args.report.resolve() if args.report else output_path.with_name(f"{output_path.stem}_pending_changes.xlsx")

    try:
        run_id = make_run_id()
        old_snapshot = load_snapshot(snapshot_path)
        dataset = build_dataset(args, [])
        comparison = compare_datasets(old_snapshot, dataset, run_id)

        if not old_snapshot:
            if output_path.exists() and not args.approve:
                print("A workbook already exists but no snapshot was found. Rerun with --approve to confirm overwrite.", file=sys.stderr)
                return 1
            write_workbook(output_path, dataset)
            write_content_json(content_json_path, dataset)
            save_snapshot(snapshot_path, dataset)
            print(f"Initial workbook created: {output_path}")
            print(f"Website content JSON created: {content_json_path}")
            print(f"Snapshot created: {snapshot_path}")
            return 0

        if not comparison["has_changes"]:
            print("No data changes detected.")
            print_change_summary(comparison)
            write_content_json(content_json_path, dataset)
            print(f"Website content JSON refreshed: {content_json_path}")
            if args.force:
                write_workbook(output_path, dataset)
                save_snapshot(snapshot_path, dataset)
                print(f"Workbook rewritten (forced): {output_path}")
            return 0

        write_change_report(report_path, comparison)
        print_change_summary(comparison, report_path)

        if args.no_approve:
            print("Workbook not replaced because --no-approve was used.")
            return 0

        approved = args.approve or prompt_approval()
        if not approved:
            print("Workbook not replaced. Existing workbook and snapshot are unchanged.")
            return 0

        write_workbook(output_path, dataset)
        write_content_json(content_json_path, dataset)
        save_snapshot(snapshot_path, dataset)
        print(f"Workbook updated: {output_path}")
        print(f"Website content JSON updated: {content_json_path}")
        print(f"Snapshot updated: {snapshot_path}")
        return 0
    except Exception as exc:
        print(f"MBBS AV Global scraper failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
